### ISSUE TITLE
Permission issue of the name: Classic Shell

### ISSUE THREAD

**Issue by coddec** [coddec/Classic-Shell#13] opened 2018-02-04 22:47 UTC
Help to Share the poll if you care about this project.
https://tpfuser.typeform.com/to/ZNKbN8

(Results:)
https://tpfuser.typeform.com/report/ZNKbN8/MiUlWb2BRqaMvrq4

-----
**05/05/2018**

Depend on the result of the poll, the new name will be: Classic Start

Future development will be made here: https://github.com/passionate-coder/Classic-Start

![s](https://user-images.githubusercontent.com/12678338/39660517-76f595a8-5084-11e8-84e7-34aedf6d492d.jpg)

**Comment by coddec** [comment] 2018-02-04 22:50
![screenshot-2018-2-5 classic shell user control panel view messages](https://user-images.githubusercontent.com/12678338/35783374-0148115c-0a5a-11e8-8fd4-c548ec25e397.png)

**Comment by ge0rdi** [comment] 2018-02-05 06:37
@coddec 
Could you also ask Ivo about the company name (`IvoSoft`) and copyright notice (`Copyright (C) 2009-2016, Ivo Beltchev`)?

**Comment by coddec** [comment] 2018-02-05 07:05
@ge0rdi 
Here's the answer from Ivo.
![screenshot-2018-2-5 classic shell user control panel view messages2](https://user-images.githubusercontent.com/12678338/35792036-1a44d704-0a9f-11e8-9b1d-7d6a65261f57.png)

**Comment by ge0rdi** [comment] 2018-02-05 07:25
I'm not sure his answer means that we need to use different name. You should ask him directly about whether we are supposed to change it or not.

In the original announcement thread, Ivo said:
> I would like nothing more than somebody else picking up the mantle and continue the development.

http://classicshell.net/forum/viewtopic.php?p=34939&f=4#p34939

To me it sounds like he wishes that someone will continue in his (definitely great) work.

**Comment by coddec** [comment] 2018-02-05 07:45
@ge0rdi
Ummm, based on this answer, it sounds like he suggest us to fork and continue development on the forked with new name?

> I haven't really thought about it, however I do like to retain the ownership of the Classic Shell brand.
The main idea of making it open source was to allow people to fork it and make something new.
I guess, ideally you should keep the Classic Shell repository pristine, **fork it under a new name, and continue development.**
> 
> As for copyright issues, I would like some sort of reference to the original, like include "Based on the Classic Shell source code by Ivo Beltchev" or something like that in the documentation.

**Comment by ge0rdi** [comment] 2018-02-05 07:54
Ah, sorry. I saw only first line of his response :(

So what's next?
Do you want to create new repo with different name (what should it be?) and simply revert master in actual repo to original (Ivo's) state?

**Comment by ge0rdi** [comment] 2018-02-05 08:59
I'd have one more proposal.
If you plan to create new repo, you may consider to create [organization](https://help.github.com/articles/collaborating-with-groups-in-organizations/) and create repo there.
Organization accounts are for free and you can easily add more people to the organization.

Of course if you prefer to have it as personal repo I definitely don't have any issues with that (and I'd gladly collaborate on it).

**Comment by coddec** [comment] 2018-02-05 09:37
@ge0rdi No problem!
Sounds great, can I create an organization which based on fork of this project?
Seems it's better will benefit the project more?

**Comment by ge0rdi** [comment] 2018-02-05 11:14
> Sounds great, can I create an organization which based on fork of this project?
> Seems it's better will benefit the project more?

I think you should create organization first and then fork from `coddec/Classic-Shell` from organization's account. Though I don't have any experience with this. So I guess you should just try and see :)

> But we need to come up with a new name for sure, any ideas?

Uff. This is the hardest part (at least for me) :(
I've never thought of creating completely new project out of this. I merely wanted to help with maintenance (support new compilers, Win10 versions) as I'm using CS (actually only Start Menu part) and want to use it further.
So I'm afraid I won't be of much help regarding to naming :(

I think we need to give it some time. Maybe you can also ask on original CS forums, some poll or so.

**Comment by coddec** [comment] 2018-02-05 11:20
I'll try to play with organization, see how far can I go haha.

I'll try to get the name sort out...

**Comment by ge0rdi** [comment] 2018-02-05 11:26
Not sure if it can contain `Classic-Shell` or it has to be totally different.
The thing is that many people know CS, so it may be good idea to have some reference in name.

**Comment by coddec** [comment] 2018-02-05 11:52
And I use only start menu part as well, I guess probably later, start menu part will be the only part left active sometime in the future?

Or we can discuss this issue later, we should get the name sort out first haha

Ummmm, good point

**Comment by ge0rdi** [comment] 2018-02-05 12:05
> I guess probably later, start menu part will be the only part left active sometime in the future?

Cool. At least we can agree on something ;)

Seriously, I hope nobody is really using _IE_ anymore, so `Classic IE` probably won't get much attention.
Not sure about `Classic Explorer` though. I'd say there are plenty of _explorer_ alternatives if one needs a bit more advanced file management.

`Classic Start` will make sense for the future, because well Win10 start menu has its _limitations_.

So maybe we can consider to focus on start menu replacement and then choose name like `Classic Start` (not sure if Ivo wants to keep that name too). Eventually something similar like `Classic Start Reborn` / `Alternative Start` (dunno).

**Comment by coddec** [comment] 2018-02-05 12:08
Exactly what I was thinking, I prefer to focus on start menu part. That way it will reduce the work load to maintain it as well, which is very important I guess, at least for now.

Again, same thoughts on the names. ;)

**Comment by coddec** [comment] 2018-02-05 12:49
I guess next step is to share the poll url....

https://tpfuser.typeform.com/to/ZNKbN8

Also posted here http://www.classicshell.net/forum/viewtopic.php?f=7&t=8273

**Comment by ge0rdi** [comment] 2018-02-05 12:52
Voted.

**Comment by coddec** [comment] 2018-02-05 12:55
Cool, thanks for voting and proving the form works! XD

Not so sure if it has anti-spam function though...

**Comment by ge0rdi** [comment] 2018-02-05 12:57
> Not so sure if it has anti-spam function though...

Hope you won't regret it :)

**Comment by coddec** [comment] 2018-02-05 12:58
Results link if anyone interested: https://tpfuser.typeform.com/report/ZNKbN8/MiUlWb2BRqaMvrq4

**Comment by coddec** [comment] 2018-02-05 13:00
Just checked, seems it has some sort of anti-spam function, ummmm, good

Now let's wait on results...

**Comment by ge0rdi** [comment] 2018-02-05 13:01
Also maybe you should check with Ivo whether he is OK with picking name that contains `Classic Start`.
Or have you already?

**Comment by coddec** [comment] 2018-02-05 13:02
Haven't yet... Personally think it's fine. I will pm him now.

**Comment by smz** [comment] 2018-02-05 13:18
Hello guys! Nice to see that you're moving forward with this!

Do not forget to ask Ivo about "non-code" material that could be copyrighted (e.g.: icons and other graphic material).

An "Organization" (_in the GitHub meaning_) is a good idea, but if you move forward I guess you should also make that organization a "legal entity" (_with all the bothering paperwork that comes with that, I know..._)

As for the name... I was thinking about "Classic Start Menu", but it seems it's already taken. If any Idea will pop-up in my mind I'll let you know...

Have you considered the possibility of bringing forward only the "Start Menu" component of "Classic Shell" and leave "Classic IE" and "Classic Explorer" behind? I've never found them of great use to me and it's a long time that I don't install them any more...

**Comment by coddec** [comment] 2018-02-05 13:24
I guess we will need to redesign most of the non-code parts too, based on Ivo's previous reply.

For the legal entity part. I guess we can ignore it if we do not check "This account is owned by a business." we should be able to safely ignore the paperwork? (See attached image)

Thanks for the name part, I'm not good at thinking name too...

That what ge0dri and me was talking about, I guess in the future, we will only keep the start menu part.

**Comment by smz** [comment] 2018-02-05 13:39
> For the legal entity part. I guess we can ignore it if we do not check "This account is owned by a business." we should be able to safely ignore the paperwork? (See attached image)

That's important not only to fulfill GitHub requirement but also for your own protection and for the one of the contributing members. Imagine a couple of scenarios:

- Microsoft sues. Are you ready to loose your house and car on that?
- After some time you "go commercial". What is protecting all the ones that have contributed to the project?

> That what ge0dri and me was talking about, I guess in the future, we will only keep the start menu part.
+1 from me!

**Comment by smz** [comment] 2018-02-05 13:57
Names:

- "Open Start Menu", underlying it's a FOSS project (_and it also reminds the action of opening the start menu..._)
- "Legacy Start Menu"

**Comment by ge0rdi** [comment] 2018-02-05 14:05
> That's important not only to fulfill GitHub requirement but also for your own protection and for the one of the contributing members.

I think we just need _organization_ account to not have this repo under one's personal user account. People are coming and leaving. So it could be hosted under some _neutral_ account.

I don't think the intent is to _go commercial_ on this one (at any point).

**Comment by ge0rdi** [comment] 2018-02-05 14:09
https://help.github.com/articles/differences-between-user-and-organization-accounts/
> Organizations are shared accounts where groups of people can collaborate across many projects at once.

**Comment by spitfireCH** [comment] 2018-02-05 19:03
> And I use only start menu part as well, I guess probably later, start menu part will be the only part left active sometime in the future?
Well, there is another component of Classic Shell that I find very useful. It is well hidden and many people probably don't even know that this function is due to Classic Shell:
If you hold down Ctrl in Windows Explorer and click / double click on a folder, the folder will open in a new window. This eliminates the hassle of using the context menu to do the same. It would be a pity to lose this function.

**Comment by smz** [comment] 2018-02-05 19:38
> If you hold down Ctrl in Windows Explorer and click / double click on a folder, ...

That's nice and I didn't know about that!

I'm wondering, anyway, if that could be handled by some specific "_mouse actions customization_" software.
I never tried any of them, but I see there is a list [here](https://www.raymond.cc/blog/changing-and-customizing-your-mouse-buttons-actions/) (_and very likely in many other places: Google is our friend. Well... sometimes._)

**Comment by SideToe** [comment] 2018-02-05 21:43
I don't want to seem like I don't care about all of the work that Ivo Beltchev / IvoSoft did but there is no trademark for Classic Shell. While the code is copyright the trade name is not registered. That being said it would make sense to do something like Classic Shell Open or something referencing the fact this is the open source versions of the Classic Shell applications.

**Comment by spitfireCH** [comment] 2018-02-05 23:08
> I'm wondering, anyway, if that could be handled by some specific "mouse actions customization" software.
I never tried any of them, but I see there is a list here (and very likely in many other places: Google is our friend. Well... sometimes.)

Thanks for the list, I am already using X-Mouse, but didn't know the others. There are some interesting tools. However, those "mouse actions customization" tools usually trigger macros. What Classic Shell does, does not look like a macro - it seems to directly access some feature hidden in Windows. I have already googled many times for this, but never found anything. Only by chance I figured out this feature was enabled by Classic Shell. So, if you ever stumble across the part of the code that does this, please let me know :)

**Comment by coddec** [comment] 2018-02-06 00:38
@smz @ge0rdi 
> I think we just need organization account to not have this repo under one's personal user account. People are coming and leaving. So it could be hosted under some neutral account.

> I don't think the intent is to go commercial on this one (at any point).

Yes, besides I didn't find any clue about paperwork regarding to create an organization account.

@SideToe 
> I don't want to seem like I don't care about all of the work that Ivo Beltchev / IvoSoft did but there is no trademark for Classic Shell. While the code is copyright the trade name is not registered. That being said it would make sense to do something like Classic Shell Open or something referencing the fact this is the open source versions of the Classic Shell applications.

Yes, technically that is right, anyone can register that as a trademark as long as there's no one registered yet.
But ethically, we should ask and follow Ivo's will since he is the founder, all of those are his work. Imagine you created a software called A.B.C and then the next day someone else registered A.B.C as their trademark, you are left out to either change the name or pay them.

That is not good :)

@spitfireCH 
> Well, there is another component of Classic Shell that I find very useful. It is well hidden and many people probably don't even know that this function is due to Classic Shell:
If you hold down Ctrl in Windows Explorer and click / double click on a folder, the folder will open in a new window. This eliminates the hassle of using the context menu to do the same. It would be a pity to lose this function.

Try ctrl+shift+double mouse click or ctrl+shift+enter will open the folder in new window, built-in windows function. Enjoy ;)

**Comment by coddec** [comment] 2018-02-06 00:41
![screenshot-2018-2-6 classic shell view topic - poll new name for open source classic shell](https://user-images.githubusercontent.com/12678338/35836133-b0a486f2-0b32-11e8-8809-ee4e3999b24f.png)

**Comment by XenHat** [comment] 2018-02-07 08:08
Sorry for chiming in late, I am having some issues sorting the massive amount of emails I get every day
@coddec I'm fine with only actively maintaining the Start Menu part.
I don't really use the Classic Explorer functions myself, and __Classic IE__, well... You know.

I think we should still offer the old version under "Looking for Classic Explorer?" handling, but point to the latest work by default.

**Comment by coddec** [comment] 2018-02-07 08:51
@XenHat 
No problem at all :)
I think it is good to keep the original name, but as replied by Ivo, he wants to keep the brand name and suggested us to fork under new name to continue to develop/maintain.
Yes I agree, credit/reference to him Ivo is essential I think. (Guess the "About" will be on the ToDo list? :D)

**Comment by spitfireCH** [comment] 2018-02-07 22:59
@coddec 
> Try ctrl+shift+double mouse click or ctrl+shift+enter will open the folder in new window, built-in windows function. Enjoy ;)

Thx for the hint, I didn't know about that! However, I couldn't quite reproduce it. I tested it on a Windows 10 machine without Classic Shell installed:

- ctrl+shift+double click did nothing.
- ctrl+double click on a folder opened the folder in a new window, just like with Classic Shell.
- Ctrl+shift+click on a folder in the navigation pane (left side of the window) did nothing (or opened in the same window, don't remember)
- Ctrl+click on a folder in the navigation pane opened in the same window
- Ctrl+click with Classic Shell installed on a folder in the navigation pane opened the folder in a new window

The last point seems to be something added by Classic Shell.

**Comment by coddec** [comment] 2018-02-08 03:19
@spitfireCH 
Umm, my mistake, ctrl+enter/double click is built-in windows function, will open folder in new window.

However, with the navigation panel this will not work.

I tried with classic shell (start menu part) installed, the ctrl+click won't open in new window from navigation panel. Unfortunately it looks like this is function might come with explorer part, not start menu part.

**Comment by B00ze64** [comment] 2018-02-08 03:20
@XenHat You might not use Classic Explorer, but I do, a LOT; I use a custom toolbar, and it is incredibly useful. I also use it so I can restore the "hand" icon over shared folders, and to replace the incredibly bad "conflict" pop-up when copying files. I'm definitively not in favor of dropping this, it's part of what makes Classic Shell different than Start 8 or other start menu replacements.

**Comment by XenHat** [comment] 2018-02-08 03:39
I'm not saying we should drop it, but hacking into the everchanging API might make the call for us. I'm not against maintaining it as long as possible, but we can't make the impossible.

**Comment by coddec** [comment] 2018-02-08 04:02
@B00ze64 
> I'm not saying we should drop it, but hacking into the everchanging API might make the call for us. I'm not against maintaining it as long as possible, but we can't make the impossible.

And it needs time to do so too :)

Anyway, I agree with XenHat, besides if anyone interested in keep the project going, feel free to ask to join the team.

https://github.com/passionate-coder

**Comment by larsen0815** [comment] 2018-02-08 08:32
Perhaps you could add "Good old shell" to the vote.

And what about Shelly McShellface? ;-)

**Comment by coddec** [comment] 2018-02-08 08:56
Good old shell added what is Shelly McShellface???

**Comment by larsen0815** [comment] 2018-02-08 08:59
See https://en.wikipedia.org/wiki/Boaty_McBoatface

**Comment by XenHat** [comment] 2018-02-09 10:53
Not quite professional enough imho...

**Comment by wcsh** [comment] 2018-02-10 08:35
I would like to throw in my 2 cents if you don't mind. From what I gleam from Ivo's response is this. He wants to retain the "" ownership of the brand "Classic Shell" All this means as long as the new people taking it over don't want to monetize it, and just put in a line "Originally Created by …" that should suffice his wishes. However if you plan to monetize it then you would defiantly have to rename it, or work out a deal where Ivo would become a shareholder or something like that. My suggestion would be if you are going to monetize it "as you call it, Fork it" rename it and then alter the code and start with a new version number. 

I really like the software completely, and use it on all my desktops and customers Desktops and all my servers. Its such a blessing to have had this come along. 
If you all ever need assistance in getting this going again "i'm no programmer" I hope that there is someway I could help. There are so many different directions you can go with this little gem:)

**Comment by coddec** [comment] 2018-02-10 08:55
@ge0rdi @XenHat 
>I would like to throw in my 2 cents if you don't mind. From what I gleam from Ivo's response is this. He wants to retain the "" ownership of the brand "Classic Shell" All this means as long as the new people taking it over don't want to monetize it, and just put in a line "Originally Created by …" that should suffice his wishes. However if you plan to monetize it then you would defiantly have to rename it, or work out a deal where Ivo would become a shareholder or something like that. My suggestion would be if you are going to monetize it "as you call it, Fork it" rename it and then alter the code and start with a new version number.
> 
> I really like the software completely, and use it on all my desktops and customers Desktops and all my servers. Its such a blessing to have had this come along.
If you all ever need assistance in getting this going again "i'm no programmer" I hope that there is someway I could help. There are so many different directions you can go with this little gem:)


Nice 2 cents from different perspective!

**Comment by coddec** [comment] 2018-02-10 08:57
@wcsh 
I won't monetize it :)
I guess @ge0rdi  and @XenHat won't too

**Comment by XenHat** [comment] 2018-02-12 12:24
> @wcsh
I won't monetize it :)
I guess @ge0rdi and @XenHat won't too

Nope. It was free, it will continue to be free.
I've been on the user end of a few products that used to be free, only to turn into pay-to-use software and I don't wish to become what I hate. 😄

**Comment by coddec** [comment] 2018-02-12 12:28
hahaha, TRUE!

**Comment by RogerSanders** [comment] 2018-02-16 04:22
I think you should re-brand. The name "Classic Shell" is limiting, as it implies the project itself is somehow constrained to restoring/mimicking an "old" style of start menu. This extension can provide far more than that, experimenting with new and totally different start menu designs that have never existed before. Now that it's open source, I won't be at all surprised if you get people attempting to do just that. Even with the existing functionality, I bet many people create configure layouts that aren't direct mirrors of old designs anyway. For example, I use classic shell to give me a trimmed down two-column start menu similar to Windows 7, but with the cascading menus from it like XP. The windows start menu has never been able to do that, and I think it's a better layout than anything Microsoft has ever produced. I don't use Classic Shell to restore old start menu behaviour, I use it to improve on the (currently abysmal IMO) Windows 10 behaviour. I don't care if what it provides is "classic" or not, I just want something usable.

Unfortunately "Power Shell" is taken, or I'd suggest that. Not sure "Power Start Menu" is quite as catchy, but I think you want a name implying it's an enhancement on the Windows start menu, not simply restoring an old version of it. For what it's worth, I also think the project should be constrained to the start menu only, as was briefly discussed above. You should split the other features into standalone tools if they're to be kept IMO. If we're doing that, the word "shell" doesn't really fit either, nor does the idea of preserving the "classic shell" branding if the product is splitting into bits. That's more reasons to re-brand.

**Comment by coddec** [comment] 2018-02-16 04:28
Hum, good points here! 👍

**Comment by Aokromes** [comment] 2018-03-05 09:29
Classic Shell Reborn :) on that way people trying to find Classic Shell will find new project. (it also can imply the classic shell is improved) :)

**Comment by auanasgheps** [comment] 2018-03-05 09:30
I agree with Classic Shell Reborn!

**Comment by david-rahrer** [comment] 2018-03-26 02:32
How about "Start Again" if you have to stay away from the original name entirely. FWIW, I've only ever used the start menu part as well.

**Comment by coddec** [comment] 2018-03-26 02:37
@david-rahrer Added

**Comment by siana** [comment] 2018-05-01 06:00
If at all possible, i'd prefer keeping the name or making a really trivial modification if demanded, like "Open Classic Shell", or if that isn't available, "Open Shell".

I don't feel that the wording "Classic Shell" is particularly limiting, unless classic Start menu is slated to be removed. I think regardless of any additional functionality that may grow on top eventually, the main draw will be a legacy start menu. And after all, if the project is not-for-profit in nature, you don't have to care about marketing, but about keeping existing users that happened to stumble on it and have grown to depend on it happy.

**Comment by blackcrack** [comment] 2018-05-01 07:01
Or may Libre Classic Shell named ... \*g\*
Naa, the software iss original, the Name should stay original .. and now it is open source, so, what's the matter .. imho should stay original, also in name. 
best regards
Blacky

**Comment by blackcrack** [comment] 2018-05-02 04:04
aye :+1:

**Comment by GottZ** [comment] 2018-05-02 12:56
so we can close this issue now and stay with classic shell? 💃

**Comment by coddec** [comment] 2018-05-02 13:41
> so we can close this issue now and stay with classic shell? 💃

Nah, based on Ivo's reply, strictly speaking, everyone who decide to develop based on his work should use a new name and left credit to him to indicate his previous work.

So we still NEED to come up with a new name.

**Comment by auanasgheps** [comment] 2018-05-02 14:31
What's wrong with the winner of the poll, Classic Start? I like it.

**Comment by SideToe** [comment] 2018-05-02 21:58
Since there are several primary functions for this utility / software would it make since to have a name to the product family and separate names for the sub-products.  This would align with the potential to separate portions of the code into their respective functions and separate maintenance.

An example for the name like the following;
Windows Enhancement Suite (WES)
WES: Start
WES: Explorer
WES: ...

I know that this breaks the linkage to the historical name _Classic Shell_ but would allow for a name that better represents what the software actually does. 

Thoughts?

**Comment by GottZ** [comment] 2018-05-02 22:04
hm. why didn't anyone think of „Classic Menu“ yet?

**Comment by Darthagnon** [comment] 2018-05-03 14:13
I'd like to leave my vote for the name @david-rahrer suggested: "Start Again" - genius. As long as the name is always cited with a subtitle akin to "Based on Classic Shell, by Ivo Beltchev", it should show up in search queries, no?

**Comment by XenHat** [comment] 2018-05-03 23:14
I do like "Start Again", however the current code has a Windows Explorer component, and the name wouldn't really fit unless we do something such as "Start Again: Explorer Plugin"

**Comment by david-rahrer** [comment] 2018-05-04 00:14
I wasn't sure the Explorer portion was going to be kept, but I suppose it
could be Start Again, Explorer Again - especially if they are split into
separate packages. One day we may need Control Panel Again :( Otherwise,
listing the Explorer Plugin under Start Again doesn't seem too bad. I would
think the Explorer part might be harder to keep working as Windows changes,
and for me it is less important (though someone else may depend on it). For
me, anything but that awful Windows 10 start menu.

On Thu, May 3, 2018 at 7:14 PM Xenhat <notifications@github.com> wrote:

> I do like "Start Again", however the current code has a Windows Explorer
> component, and the name wouldn't really fit unless we do something such as
> "Start Again: Explorer Plugin"
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/db669b774a9677d1b4bff9694fa0907bd3da3e13?url=https%3A%2F%2Fgithub.com%2Fcoddec%2FClassic-Shell%2Fissues%2F13%23issuecomment-386464435&userId=1869741&signature=d40ced5fe497dae8>,
> or mute the thread
> <https://mailtrack.io/trace/link/f1bb76ccd65e4c972a18f3d4831d3faf6f2fafce?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAjpif9hErs2OUne0_wJ-fZtx8RQCyPdks5tu49wgaJpZM4R4wvU&userId=1869741&signature=18a99ead96feafee>
> .
>
-- 

David Rahrer

**Comment by blackcrack** [comment] 2018-05-04 05:09
>hm. why didn't anyone think of „Classic Menu“ yet?
>after all, the start menu replacement is the core idea behind classic shell or am i wrong?

because they want with all might an other name they bumbatz .. instead 
to hold the old good -known- name and want make all broken because of that,
because with the name it's all bull or baer and the well known name should stay
and this discussion should close and never open !

best regards
Blackcrack

**Closed** 2018-05-05 06:53 UTC

**Comment by coddec** [comment] 2018-05-05 07:27
The new name will be Classic Start.
Future development will be made here: https://github.com/passionate-coder/Classic-Start
